### ISSUE TITLE
Not able to install dependencies and start app

### ISSUE THREAD

**Issue by prayuj** [Meta-Games-Biz/Kings-Corner#120]
## Description

I am trying to install dependencies using `npm install` but it's throwing an error.

## Steps To Reproduce

1. `nvm install 14.16.1`
2. `nvm use 14.16.1`
3. `npm install && npm start`

## Expected Behavior

Packages to install and app to start.

## Screenshot

![image](https://user-images.githubusercontent.com/30574783/120761788-2d5cea00-c533-11eb-8c44-8a057077ec41.png)

## Platform (Please Complete The Following Information)

 - OS: Windows10
 - Browser: None

## Additional Context

[Here](https://github.com/Meta-Games-Biz/Kings-Corner/files/6596503/2021-06-04T07_12_11_441Z-debug.log) is the log of the error.

**Comment by mrrosoff** [comment]
Please try using `--force` as suggested, many npm packages have not updated their dependencies for React 17 yet.

I will commit `package-lock.json` now that primary development is done to avoid this problem in the future.
