### ISSUE TITLE
Click Avatar To Go To User Profile

### ISSUE THREAD

**Issue by matthewfernst** [Meta-Games-Biz/Kings-Corner#64]
## Problem Statement

It would be nice to be able to easily access profile data on a user when navigating the application. To this end, I propose allowing the user to click on near any avatar to jump directly to that users profile.

## Proposed Solution

Proposed solution is described above. Initial thoughts make me believe that having a profile button next to the message icon in search would be a better fit for that component, but perhaps supporting both in search is the way to go. Will allow assignee to decide.

## Additional Context

Depends on #66

**Comment by mrrosoff** [comment]
I decided that we simply won't support navigating to other's profile pages. Therefore closing this issue.
